on:
  workflow_dispatch:
jobs:
  run_ci_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: basic testing
        shell: bash
        run: |
          ./run_gh_ci.sh
